"""
Tests for src/numerical/point_projection.py -- the two validation
checks developed during initial implementation, formalized as pytest.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import numpy as np
import pytest
from numerical.point_projection import pappus_element_volume, robust_bisection_thickness


def test_pappus_matches_closed_form_cylinder():
    """For a vertical wall (rA=rB=R), Pappus's theorem must reduce
    EXACTLY to the closed-form hollow-cylinder volume."""
    R, h, t = 20.0, 15.0, 2.0
    V_pappus = pappus_element_volume(R, 0.0, R, h, t, t)
    V_analytic = np.pi * h * t * (2 * R + t)
    assert V_pappus == pytest.approx(V_analytic, rel=1e-9)


def test_bisection_recovers_known_thickness():
    """Given a volume generated by a known thickness, the solver must
    recover that same thickness."""
    rA, zA, rB, zB, t_known = 15.0, 0.0, 25.0, 10.0, 1.35
    V_target = pappus_element_volume(rA, zA, rB, zB, t_known, t_known)
    t_recovered = robust_bisection_thickness(rA, zA, rB, zB, tA=t_known, target_volume=V_target)
    assert t_recovered == pytest.approx(t_known, abs=1e-4)


def test_volume_increases_with_thickness():
    """Sanity check: element volume must be monotonically increasing
    in tB (required for the bisection solver's bracket search to be
    well-posed at all)."""
    rA, zA, rB, zB = 15.0, 0.0, 25.0, 10.0
    volumes = [pappus_element_volume(rA, zA, rB, zB, 1.0, t) for t in [0.5, 1.0, 1.5, 2.0]]
    assert all(v2 > v1 for v1, v2 in zip(volumes, volumes[1:]))


def test_degenerate_zero_length_element_raises_or_handles():
    """A zero-length element (A==B) is geometrically degenerate --
    confirm it doesn't silently return a nonsensical volume."""
    V = pappus_element_volume(20.0, 5.0, 20.0, 5.0, 1.0, 1.0)
    assert V == pytest.approx(0.0, abs=1e-6)